# Generated by Django 2.2.1 on 2020-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dalhousie_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dharamshala_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('hotel_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(default='', max_length=100)),
                ('hotel_location', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kinnaur_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='manali_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='price_of_basic_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=100)),
                ('no_of_days_plan', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='shimla_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='spiti_customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('possibility', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('transport_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('transport_name', models.CharField(default='', max_length=100)),
                ('transport_location', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('user_email', models.CharField(default='', max_length=20)),
                ('no_of_members', models.CharField(default='', max_length=20)),
                ('user_phone', models.IntegerField(default=0)),
                ('when_to_start', models.CharField(default='', max_length=10)),
                ('user_destination', models.CharField(default='', max_length=30)),
                ('user_plan', models.CharField(default='', max_length=30)),
                ('user_plan_link', models.CharField(default='', max_length=100)),
                ('user_hotel', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users1_customize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('user_email', models.CharField(default='', max_length=20)),
                ('no_of_members', models.CharField(default='', max_length=20)),
                ('user_phone', models.IntegerField(default=0)),
                ('when_to_start', models.CharField(default='', max_length=10)),
                ('user_destination', models.CharField(default='', max_length=30)),
                ('user_plan', models.CharField(default='', max_length=30)),
                ('user_plan_link', models.CharField(default='', max_length=100)),
                ('user_hotel', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
