# Generated by Django 2.2.1 on 2020-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1',
            name='user_transport',
            field=models.CharField(default='', max_length=30),
        ),
    ]
