# Generated by Django 2.2.1 on 2020-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_users1_user_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users1_customize',
            old_name='price',
            new_name='price_other',
        ),
        migrations.AddField(
            model_name='users1_customize',
            name='price_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users1_customize',
            name='user_transport',
            field=models.CharField(default='', max_length=30),
        ),
    ]
